org: robjy
app: test-wsgi-2
service: test-wsgi-2

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  deploymentBucket:
    name: rob-serverless-hits-dev

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
