org: robjy
app: test-wsgi-2
service: test-wsgi-2

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${file(./vars.yml):bucket_serverless}

  iam:
    role:
      statements:
        - Effect: Allow
          Action: "s3:*"
          Resource: 
            - "arn:aws:s3:::${file(./vars.yml):bucket_data}"
            - "arn:aws:s3:::${file(./vars.yml):bucket_data}/*"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
